is_display_login_in_effect: true
spawn_loc:
  w: 'world'
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
lock_time: 0
welcome_title: '欢迎来到OurCraft服务器'
welcome_subtitle: '祝您游戏愉快'
bs_bar_msgs:
- 'm0'
- 'm1'
qrcode_kit: 'qrcode_kit'